# List of default permissions as requested
DEFAULT_PERMISSIONS = [
    "users.create",
    "users.read",
    "users.update",
    "users.delete",
    "roles.create",
    "roles.read",
    "roles.update",
    "roles.delete",
    "permissions.read",
    # Customer Management (Legacy/General)
    "customers.read",
    "customers.create",
    "customers.update",
    "customers.archive",
    "contacts.read",
    "contacts.create",
    "contacts.update",
    "contacts.delete",
    "addresses.read",
    "addresses.create",
    "addresses.update",
    "addresses.delete",
    # Customer Management (New Granular)
    "customer.read",
    "customer.create",
    "customer.update",
    "customer.delete",
    "customer.archive",
    "customer.restore",
    "customer.assign",
    "customer.import",
    "customer.export",
    "customer.analytics",
    "customer.salesforce_sync",
    "customer.contact.read",
    "customer.contact.create",
    "customer.contact.update",
    "customer.notes.read",
    "customer.notes.create",
    "customer.activity.read",
    "customer.quote_history.read",
    # Catalog
    "catalog.read",
    "catalog.create",
    "catalog.update",
    "catalog.delete",
    "catalog.archive",
    "catalog.restore",
    "catalog.pricing.read",
    "catalog.cost.read",
    "catalog.cost.manage",
    "catalog.margin.read",
    "catalog.import",
    "catalog.export",
    "pricing.read",
    "pricing.manage",
    "quotes.read",
    "quotes.create",
    "quotes.update",
    "quotes.delete",
    "quotes.approve",
    "quotes.export",
    "approval.read",
    "approval.manage",
    "system.admin"
]

# List of default roles
DEFAULT_ROLES = [
    "Administrator",
    "Sales Manager",
    "Sales Representative",
    "Executive",
    "Viewer"
]

# Default role to permission mappings for seeding
ROLE_PERMISSION_MAPPINGS = {
    "Administrator": DEFAULT_PERMISSIONS,
    "Sales Manager": [
        "users.read",
        "roles.read",
        "permissions.read",
        "customers.read",
        "customers.create",
        "customers.update",
        "customers.archive",
        "contacts.read",
        "contacts.create",
        "contacts.update",
        "contacts.delete",
        "addresses.read",
        "addresses.create",
        "addresses.update",
        "addresses.delete",
        # New customer permissions for Manager
        "customer.read",
        "customer.create",
        "customer.update",
        "customer.archive",
        "customer.restore",
        "customer.assign",
        "customer.import",
        "customer.export",
        "customer.analytics",
        "customer.salesforce_sync",
        "customer.contact.read",
        "customer.contact.create",
        "customer.contact.update",
        "customer.notes.read",
        "customer.notes.create",
        "customer.activity.read",
        "customer.quote_history.read",
        "catalog.read",
        "catalog.create",
        "catalog.update",
        "catalog.archive",
        "catalog.restore",
        "catalog.pricing.read",
        "catalog.cost.read",
        "catalog.cost.manage",
        "catalog.margin.read",
        "catalog.import",
        "catalog.export",
        "pricing.read",
        "quotes.read",
        "quotes.create",
        "quotes.update",
        "quotes.approve",
        "quotes.export",
        "approval.read",
        "approval.manage"
    ],
    "Sales Representative": [
        "customers.read",
        "customers.create",
        "customers.update",
        "contacts.read",
        "contacts.create",
        "contacts.update",
        "addresses.read",
        "addresses.create",
        "addresses.update",
        # New customer permissions for Sales Rep
        "customer.read",
        "customer.create",
        "customer.update",
        "customer.contact.read",
        "customer.contact.create",
        "customer.contact.update",
        "customer.notes.read",
        "customer.notes.create",
        "customer.activity.read",
        "customer.quote_history.read",
        "catalog.read",
        "catalog.pricing.read",
        "pricing.read",
        "quotes.read",
        "quotes.create",
        "quotes.update",
        "approval.read"
    ],
    "Executive": [
        "customer.read",
        "customer.contact.read",
        "customer.activity.read",
        "customer.quote_history.read",
        "customer.analytics",
        "customer.export",
        "catalog.read",
        "catalog.pricing.read",
        "catalog.cost.read",
        "catalog.margin.read",
        "pricing.read",
        "quotes.read",
        "approval.read"
    ],
    "Viewer": [
        "customers.read",
        "contacts.read",
        "addresses.read",
        # New customer permissions for Viewer
        "customer.read",
        "customer.contact.read",
        "customer.activity.read",
        "customer.quote_history.read",
        "catalog.read",
        "catalog.pricing.read",
        "pricing.read",
        "quotes.read",
        "approval.read"
    ]
}
