"""add_customer_owner_id

Revision ID: 9bc062223cbb
Revises: a76c430709e2
Create Date: 2026-08-15 11:46:09.633611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc062223cbb'
down_revision: Union[str, None] = 'a76c430709e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_customer_primary'), table_name='contacts', postgresql_where='(is_primary = true)')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_customer_addresses_customer_primary'), table_name='customer_addresses', postgresql_where='(is_primary = true)')
    op.add_column('customers', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_customers_tenant_customer_number'), table_name='customers')
    op.create_foreign_key(None, 'customers', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_index(op.f('ix_customers_tenant_customer_number'), 'customers', ['tenant_id', 'customer_number'], unique=True)
    op.drop_column('customers', 'owner_id')
    op.create_index(op.f('ix_customer_addresses_customer_primary'), 'customer_addresses', ['customer_id'], unique=True, postgresql_where='(is_primary = true)')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_customer_primary'), 'contacts', ['customer_id'], unique=True, postgresql_where='(is_primary = true)')
    # ### end Alembic commands ###
