"""add_billing_type_to_products

Revision ID: a67fed2fe955
Revises: ac8b161887f7
Create Date: 2026-08-15 13:59:59.002133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_billing_type_to_products

Revision ID: a67fed2fe955
Revises: ac8b161887f7
Create Date: 2026-08-15 13:59:59.002133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67fed2fe955'
down_revision: Union[str, None] = 'ac8b161887f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('billing_type', sa.String(length=20), nullable=True))
    op.execute("UPDATE products SET billing_type = 'MRC'")
    op.alter_column('products', 'billing_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'billing_type')
    # ### end Alembic commands ###
