"""update_customer_and_contacts_and_addresses

Revision ID: a76c430709e2
Revises: 401b68cd6926
Create Date: 2026-08-10 21:15:47.123740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76c430709e2'
down_revision: Union[str, None] = '401b68cd6926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=50), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_addresses_id'), 'customer_addresses', ['id'], unique=False)
    op.add_column('contacts', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('is_primary', sa.Boolean(), nullable=False))
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_external_crm_id'), table_name='contacts')
    op.drop_column('contacts', 'external_crm_id')
    op.add_column('customers', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.add_column('customers', sa.Column('customer_number', sa.String(length=50), nullable=False))
    op.add_column('customers', sa.Column('legal_name', sa.String(length=255), nullable=False))
    op.add_column('customers', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('customer_type', sa.String(length=50), nullable=False))
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('customers', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('customers', sa.Column('tax_identifier', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('customers', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('customers', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_customers_external_crm_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_index('ix_customers_tenant_customer_number', 'customers', ['tenant_id', 'customer_number'], unique=True)
    op.create_index('ix_contacts_customer_primary', 'contacts', ['customer_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_index('ix_customer_addresses_customer_primary', 'customer_addresses', ['customer_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_index('ix_contacts_email', 'contacts', ['email'], unique=False)
    op.drop_constraint('customers_account_manager_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'customers', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('customers', 'account_manager_id')
    op.drop_column('customers', 'external_crm_id')
    op.drop_column('customers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_email', table_name='contacts')
    op.drop_index('ix_customer_addresses_customer_primary', table_name='customer_addresses')
    op.drop_index('ix_contacts_customer_primary', table_name='contacts')
    op.drop_index('ix_customers_tenant_customer_number', table_name='customers')
    op.add_column('customers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('external_crm_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('account_manager_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key(op.f('customers_account_manager_id_fkey'), 'customers', 'users', ['account_manager_id'], ['id'])
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_external_crm_id'), 'customers', ['external_crm_id'], unique=True)
    op.drop_column('customers', 'updated_by')
    op.drop_column('customers', 'created_by')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'currency')
    op.drop_column('customers', 'tax_identifier')
    op.drop_column('customers', 'status')
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'email')
    op.drop_column('customers', 'customer_type')
    op.drop_column('customers', 'display_name')
    op.drop_column('customers', 'legal_name')
    op.drop_column('customers', 'customer_number')
    op.drop_column('customers', 'tenant_id')
    op.add_column('contacts', sa.Column('external_crm_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_contacts_external_crm_id'), 'contacts', ['external_crm_id'], unique=True)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    op.drop_column('contacts', 'is_primary')
    op.drop_column('contacts', 'department')
    op.drop_column('contacts', 'job_title')
    op.drop_index(op.f('ix_customer_addresses_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    # ### end Alembic commands ###
