"""add_customer_soft_delete_columns

Revision ID: fc0ed3d4368d
Revises: 9bc062223cbb
Create Date: 2026-08-15 12:00:18.370960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0ed3d4368d'
down_revision: Union[str, None] = '9bc062223cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'customers', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'deleted_by')
    op.drop_column('customers', 'deleted_at')
    # ### end Alembic commands ###
